import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { renderHtml, validateReport, writeReport } from '../../tools/niche-report/cli.mjs';

const root = path.resolve(fileURLToPath(new URL('../..', import.meta.url)));
function fixture() { return { schema_version: 1, generated_at: '2026-09-14T08:00:00Z', account: { label: '@example_creator', verified: true }, window: { start: '2026-06-16T08:00:00Z', end: '2026-09-14T08:00:00Z', requested_days: 90, expanded_days: 90, owned_post_count: 24 }, coverage: { posts_complete: true, audience_comments_complete: true, creator_replies_complete: true, gaps: [] }, evidence_method: 'provider_ranked', niche: { statement: 'I help independent experts turn audience conversations into useful content systems.', avatar: 'Independent experts', problem: 'They cannot see which audience problems deserve a content lane.', mechanism: 'Owned post and conversation evidence', why: 'The same workflow problem appears across winning posts and distinct conversations.' }, ideal_client: { label: 'The evidence-rich but positioning-poor expert', situation: 'They publish consistently but describe their niche too broadly.', pains: ['Their strongest ideas feel disconnected.'], desired_outcomes: ['A clear content lane grounded in audience response.'], language: ['I know what I do, but I cannot explain my niche.'], objections: ['My posts cover too many topics.'], purchase_intent_proven: false }, themes: [{ theme: 'Evidence before ideation', lane: 'cross_lane', observation: 'Creators respond to workflows that use owned evidence before generating.', distinct_sources: 4, evidence_refs: ['post-01', 'post-02', 'comment-theme-01', 'reply-01'] }], content_pillars: [{ name: 'Audience evidence', promise: 'Find useful signals.', example_topics: ['Read comments without overclaiming.'] }, { name: 'Content systems', promise: 'Turn signals into repeatable work.', example_topics: ['Build a weekly evidence loop.'] }, { name: 'Creator positioning', promise: 'Make expertise legible.', example_topics: ['Write an evidence-backed bio.'] }], emphasize: ['Owned evidence and visible transformations.'], stop_pursuing: ['Generic AI news without a creator job.'], next_profile_action: 'Turn the niche sentence into a bio and visual brief.', confidence: 'high', limitations: ['Engagement does not prove purchase intent.'] }; }
test('schema and runtime validator accept the complete contract', () => { const ajv = new Ajv({ strict: true }); addFormats(ajv); const validate = ajv.compile(JSON.parse(fs.readFileSync(path.join(root, 'schemas/niche-report.v1.json')))); const report = fixture(); assert.equal(validate(report), true, JSON.stringify(validate.errors)); assert.equal(validateReport(report), report); });
test('renderer writes a private self-contained report and body-free receipt', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'niche-report-')); const result = writeReport(fixture(), dir); assert.match(result.report_sha256, /^[a-f0-9]{64}$/); const html = fs.readFileSync(result.html, 'utf8'); assert.match(html, /Content-Security-Policy/); assert.doesNotMatch(html, /https?:\/\//); const receipt = JSON.parse(fs.readFileSync(result.receipt)); assert.equal(receipt.workflow_id, 'find-your-niche'); assert.equal(JSON.stringify(receipt).includes('Their strongest ideas'), false); });
test('renderer escapes untrusted theme text', () => { const report = fixture(); report.themes[0].observation = '<script>steal()</script>'; const html = renderHtml(report); assert.doesNotMatch(html, /<script>/); assert.match(html, /&lt;script&gt;/); });
test('provider ranking requires verified complete post coverage', () => { const report = fixture(); report.account.verified = false; assert.throws(() => validateReport(report), /provider_ranked/); });
