import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync, spawnSync } from 'node:child_process';
const cli = fileURLToPath(new URL('./cli.mjs',import.meta.url));
test('fresh-install CLI walkthrough creates exact send packet and resumes feedback',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'inbound-cli-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const account='@fresh', now=new Date().toISOString();
 const run=(command,data,extra=[])=>{const file=path.join(root,'packet.json');if(data)fs.writeFileSync(file,JSON.stringify({version:1,account,...data}));return JSON.parse(execFileSync(process.execPath,[cli,command,'--root',path.join(root,'state'),'--account',account,...(data?['--packet',file]:[]),...extra],{encoding:'utf8'}));};
 assert.equal(run('window').preference_required,true);
 run('configure',{preference:'all',timezone:'UTC'});
 const window=run('window');
 const snapshot=run('import',{...window,coverage:{complete:true,gaps:[]},items:[{source_id:'native-example',lane:'mention',author:'@reader',text:'a question',occurred_at:window.start,pending:true,safety:'safe',available:true,context_complete:true,post:{text:'full context'},ancestry:[]}]});
 let i=snapshot.items[0];
 i=run('drafts',{drafts:[{id:i.id,source_id:i.source_id,revision:i.revision,text:'reply\n🌿  ',mode:'agent',context_verified:true,gates_passed:true}]}).items[0];
 i=run('decide',{id:i.id,revision:i.revision,action:'approve'});
 const final_hash=createHash('sha256').update(i.final_text).digest('hex');
 const attempt=run('prepare-send',{authorization:{explicit:true,reference:'synthetic-user-message'},items:[{id:i.id,revision:i.revision,source_id:i.source_id,author:i.author,final_hash,pending:true,safe:true,available:true,gates_passed:true,evidence_ref:'synthetic-live-check',checked_at:new Date().toISOString()}]});
 assert.deepEqual(attempt.mcp.drafts,[{mention_id:i.source_id,text:'reply\n🌿  '}]);
 run('record-send',{key:attempt.attempt.key,receipt:'synthetic-send-receipt'});
 const state=run('reconcile',{key:attempt.attempt.key,results:[{id:i.id,source_id:i.source_id,author:i.author,status:'published',evidence_ref:'synthetic-independent-read',checked_at:new Date().toISOString(),text:i.final_text,reply_id:'synthetic-reply',url:'https://www.threads.com/example',pending_before:true,replied_after:true}]});
 assert.equal(state.items[0].state,'published');assert.equal(state.feedback_pending.length,1);
 run('feedback',{key:state.feedback_pending[0].key,receipt:'synthetic-feedback'});
 assert.equal(run('close',{}).feedback_pending,0);
 assert.equal(run('window').start,window.end);
 const bad=spawnSync(process.execPath,[cli,'status','--account',account,'--root',path.join(root,'state')],{encoding:'utf8'});assert.equal(bad.status,0);
});
import { createHash } from 'node:crypto';
