import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { Store, hash, editorSurface, learning } from './store.mjs';
import { serve } from './server.mjs';
const account = '@example';
const now = '2026-01-02T00:00:00.000Z';
const p = value => ({version:1,account,...value});
function fixture(t, count = 2) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'inbound-test-')); t.after(() => fs.rmSync(root,{recursive:true,force:true}));
  const store = new Store(root, () => new Date(now));
  store.configure(p({preference:'five',timezone:'UTC'}));
  const items = Array.from({length:count},(_,i)=>({source_id:'c'+i,lane:'comment',author:'@reader'+i,text:'Comment '+i,url:'https://www.threads.com/comment'+i,occurred_at:`2026-01-01T0${i%9}:00:00Z`,pending:true,available:true,safety:'safe',context_complete:true,ancestry:[],post:{id:'p'+(i%2),verified:true,text:'A complete old post',url:'https://www.threads.com/post'+(i%2)}}));
  const snapshot=p({start:'2026-01-01T00:00:00Z',end:now,coverage:{complete:true,gaps:[]},items});
  store.import(snapshot);
  return {store,root,snapshot,items:()=>store.status(account).items};
}
function draft(store,item,value='Hello\n🌱  ',mode='native') { store.drafts(p({drafts:[{id:item.id,source_id:item.source_id,revision:item.revision,text:value,mode,context_verified:true,gates_passed:true}]})); return store.status(account).items.find(i=>i.id===item.id); }
function approve(store,item) { return store.decide(p({id:item.id,revision:item.revision,action:'approve'})); }
function prepare(store,items) { return store.prepare(p({authorization:{explicit:true,reference:'synthetic-user-approval'},items:items.map(i=>({id:i.id,source_id:i.source_id,author:i.author,revision:i.revision,final_hash:hash(i.final_text),pending:true,safe:true,available:true,gates_passed:true,evidence_ref:'synthetic-read',checked_at:now}))})); }
function published(item){return {id:item.id,source_id:item.source_id,author:item.author,status:'published',text:item.final_text,reply_id:'reply-'+item.source_id,url:'https://www.threads.com/reply-'+item.source_id,pending_before:true,replied_after:true,evidence_ref:'independent-synthetic-read',checked_at:now};}
test('group native parents contiguously and retain all safe praise',t=>{const {items}=fixture(t,8); assert.equal(items().length,8); const groups=items().map(i=>i.group); assert.deepEqual(groups,['post:p0','post:p0','post:p0','post:p0','post:p1','post:p1','post:p1','post:p1']);});
test('arbitrary windows and old parent posts use comment timestamps',t=>{const {store}=fixture(t); const w=store.window(account,{period:'7d'});assert.equal(Date.parse(w.end)-Date.parse(w.start),7*864e5);assert.equal(store.status(account).items.length,2);});
test('account isolation and saved preferences survive restart',t=>{const {store,root}=fixture(t); store.configure({version:1,account:'@other',preference:'all',timezone:'Europe/London'}); const next=new Store(root); assert.equal(next.status(account).preference,'five'); assert.equal(next.status('@other').preference,'all');assert.equal(next.status('@other').items.length,0);});
test('exact edits revoke approval and conflicts never overwrite',t=>{const {store,items}=fixture(t); let i=approve(store,draft(store,items()[0])); const revision=i.revision; i=store.edit(p({id:i.id,revision,text:'café\n\n🌱  '})); assert.equal(i.final_text,'café\n\n🌱  '); assert.equal(i.state,'drafted');assert.equal(i.approved_revision,undefined);assert.throws(()=>store.edit(p({id:i.id,revision,text:'stale'})),/revision_conflict/);});
test('blank and untouched replies never approve implicitly',t=>{const {store,items}=fixture(t); assert.equal(items()[0].state,'captured'); assert.throws(()=>approve(store,items()[0]),/nonblank/);const i=draft(store,items()[0]);assert.equal(i.state,'drafted');});
test('native draft binding rejects wrong IDs and incomplete context',t=>{const {store,items}=fixture(t);const i=items()[0];assert.throws(()=>store.drafts(p({drafts:[{id:i.id,revision:0,source_id:'wrong',text:'x',mode:'native',context_verified:true,gates_passed:true}]})),/binding/);});
test('regeneration retains original draft and changes latest baseline',t=>{const {store,items}=fixture(t); let i=draft(store,items()[0],'first');i=store.decide(p({id:i.id,revision:i.revision,action:'regenerate'}));i=draft(store,i,'second','agent'); assert.equal(i.original_text,'first');assert.equal(i.draft_text,'second');assert.equal(i.history.filter(h=>h.type==='draft').length,2);});
test('defer reappears next run; skip persists with undo',t=>{const {store,items}=fixture(t);for(const [index,action] of [[0,'defer'],[1,'skip']])store.decide(p({id:items()[index].id,revision:0,action}));store.close(p({}));store.import(p({start:now,end:'2026-01-03T00:00:00Z',coverage:{complete:true,gaps:[]},items:[]}));assert.equal(items().length,1);assert.equal(items()[0].state,'captured'); const skipped=Object.values(store.read(account).items).find(i=>i.state==='skipped');store.decide(p({id:skipped.id,revision:skipped.revision,action:'undo'}));assert.equal(store.read(account).items[skipped.id].state,'drafted');});
test('incomplete coverage never advances checkpoint',t=>{const {store,root,snapshot}=fixture(t); const other='@gap';store.configure({version:1,account:other,preference:'all',timezone:'UTC'});store.import({...snapshot,account:other,coverage:{complete:false,gaps:['mentions capped']},items:[]});assert.equal(store.close({version:1,account:other}).checkpoint,null);assert.equal(new Store(root).read(other).checkpoint,null);});
test('immutable reimport and active batch conflict',t=>{const {store,snapshot}=fixture(t);assert.equal(store.import({...snapshot,items:[]}).items.length,2);assert.throws(()=>store.import({...snapshot,end:'2026-01-03T00:00:00Z'}),/open_batch_exists/);});
test('excluded private Quest IDs never enter batch',t=>{const {store,snapshot}=fixture(t);store.configure({version:1,account:'@exclude',preference:'all',timezone:'UTC'});const result=store.import({...snapshot,account:'@exclude',exclude_ids:['c0']});assert.equal(result.items.length,1);});
test('send requires chat authorization and exact approved revisions',t=>{const {store,items}=fixture(t);const i=draft(store,items()[0]);assert.throws(()=>prepare(store,[i]),/approved/);assert.throws(()=>store.prepare(p({items:[]})),/authorization/);});
test('durable attempt blocks duplicates and edits through restart',t=>{const {store,root,items}=fixture(t);const i=approve(store,draft(store,items()[0]));const prepared=prepare(store,[i]);const next=new Store(root,()=>new Date(now));assert.equal(next.status(account).attempts[0].key,prepared.attempt.key);assert.throws(()=>prepare(next,[i]),/approved/);assert.throws(()=>next.edit(p({id:i.id,revision:i.revision,text:'change'})),/in_flight/);});
test('partial success, uncertain delivery and feedback retries do not resend',t=>{const {store,items}=fixture(t);const selected=items().map(i=>approve(store,draft(store,i)));const attempt=prepare(store,selected);store.recordSend(p({key:attempt.attempt.key,receipt:'synthetic-queue'}));store.reconcile(p({key:attempt.attempt.key,results:[published(selected[0]),{...published(selected[1]),status:'uncertain'}]}));assert.equal(items()[0].state,'published');assert.equal(items()[1].state,'uncertain');assert.throws(()=>prepare(store,[selected[0]]),/approved/);const f=store.status(account).feedback_pending[0];store.feedback(p({key:f.key,receipt:'feedback-ok'}));store.feedback(p({key:f.key,receipt:'retry'}));assert.equal(store.status(account).feedback_pending.length,0);assert.equal(store.status(account).learning.native.recent.count,1);});
test('mismatched published text is rejected atomically',t=>{const {store,items}=fixture(t);const i=approve(store,draft(store,items()[0]));const a=prepare(store,[i]);store.recordSend(p({key:a.attempt.key,receipt:'queued'}));assert.throws(()=>store.reconcile(p({key:a.attempt.key,results:[{...published(i),text:'wrong'}]})),/text_mismatch/);assert.equal(items()[0].state,'queued');assert.equal(store.status(account).feedback_pending.length,0);});
test('definitive failure needs proof and a new approval before retry',t=>{const {store,items}=fixture(t);const i=approve(store,draft(store,items()[0]));const a=prepare(store,[i]);const failure={...published(i),status:'failed',definitely_not_sent:true,failure_receipt:'provider-failed-before-send'};store.reconcile(p({key:a.attempt.key,results:[failure]}));assert.equal(items()[0].state,'drafted');assert.throws(()=>prepare(store,[items()[0]]),/approved/);const next=prepare(store,[approve(store,items()[0])]);assert.notEqual(next.attempt.key,a.attempt.key);});
test('live checks expire and must bind exact bytes',t=>{const {store,items}=fixture(t);const i=approve(store,draft(store,items()[0]));const request=p({authorization:{explicit:true,reference:'user'},items:[{...i,final_hash:hash(i.final_text),pending:true,safe:true,available:true,gates_passed:true,evidence_ref:'read',checked_at:'2026-01-01T23:00:00Z'}]});assert.throws(()=>store.prepare(request),/expired/);});
test('locks fail closed and files are private',t=>{const {store}=fixture(t);const file=store.file(account);fs.writeFileSync(file+'.lock','busy');assert.throws(()=>store.configure(p({preference:'all',timezone:'UTC'})),/locked/);assert.equal(fs.statSync(file).mode&0o777,0o600);});
test('native surface requires every capability',()=>{assert.equal(editorSurface({create:true,stableIdentity:true}),'local');assert.equal(editorSurface({create:true,stableIdentity:true,readback:true}),'native');});
test('learning separates modes and requires two comparable samples',()=>{const rows=Array.from({length:40},(_,i)=>({mode:'native',created:String(i).padStart(2,'0'),baseline_text:'hello',final_text:'hi'}));assert.equal(learning(rows).native.comparison,'comparable_samples_not_causal');assert.equal(learning(rows).agent.recent.count,0);assert.equal(learning(rows).native.recurring_corrections.shortened,40);});
test('loopback server protects mutations, rejects cross origin and never sends',async t=>{const {store,items}=fixture(t);const {server,url}=await serve(store,account);t.after(()=>server.close());const u=new URL(url),origin=u.origin,token=u.hash.slice(1);const headers={'X-Review-Session':token,'Content-Type':'application/json'};assert.equal((await fetch(origin+'/api/status')).status,403);assert.equal((await fetch(origin+'/api/status',{headers:{...headers,Origin:'https://evil.example'}})).status,403);assert.equal((await fetch(origin+'/api/send',{method:'POST',headers,body:'{}'})).status,404);const i=items()[0];const result=await fetch(origin+'/api/edit',{method:'POST',headers,body:JSON.stringify({id:i.id,revision:i.revision,text:'Exact\n  🌱'})});assert.equal(result.status,200);assert.equal((await result.json()).final_text,'Exact\n  🌱');assert.equal((await fetch(origin+'/api/edit',{method:'POST',headers,body:JSON.stringify({id:i.id,revision:0,text:'stale'})})).status,409);assert.match((await fetch(origin)).headers.get('content-security-policy'),/frame-ancestors 'none'/);});
test('incomplete context can be enriched without reopening frozen cohort',t=>{const {store,items}=fixture(t);const i=items()[0];store.transaction(account,s=>{s.items[i.id].context_complete=false;});assert.throws(()=>draft(store,items()[0]),/binding/);const updated=store.context(p({id:i.id,revision:0,evidence_ref:'live-context',source:{source_id:i.source_id,author:i.author,safe:true,pending:true,available:true,text:i.text,post:i.post,ancestry:[],context_complete:true}}));assert.equal(updated.context_complete,true);assert.equal(draft(store,updated).state,'drafted');});
test('context changes revoke approval and cannot change target parent',t=>{const {store,items}=fixture(t);const i=approve(store,draft(store,items()[0]));const request=p({id:i.id,revision:i.revision,evidence_ref:'read',source:{source_id:i.source_id,author:i.author,safe:true,pending:true,available:true,text:'Updated inbound',post:i.post,ancestry:[],context_complete:true}});const changed=store.context(request);assert.equal(changed.state,'drafted');assert.equal(changed.approved_revision,undefined);assert.throws(()=>store.context({...request,revision:changed.revision,source:{...request.source,post:{...i.post,id:'wrong'}}}),/parent_identity/);});
test('receipt excludes raw posts, comments and reply bodies',t=>{const {store,items}=fixture(t);const i=approve(store,draft(store,items()[0],'Distinct private reply body'));const a=prepare(store,[i]);store.recordSend(p({key:a.attempt.key,receipt:'queued'}));store.reconcile(p({key:a.attempt.key,results:[published(i)]}));const receipt=JSON.stringify(store.receipt(account));assert.equal(receipt.includes('Distinct private reply body'),false);assert.equal(receipt.includes('A complete old post'),false);assert.equal(receipt.includes('Comment 0'),false);assert.equal(store.receipt(account).feedback_pending,1);});
test('the same native source discovered in comments and mentions is queued once',t=>{const {store,snapshot}=fixture(t);store.configure({version:1,account:'@crosslane',preference:'all',timezone:'UTC'});const duplicate={...snapshot.items[0],lane:'mention'};const result=store.import({...snapshot,account:'@crosslane',items:[snapshot.items[0],duplicate]});assert.equal(result.items.length,1);assert.equal(result.items[0].lane,'comment');});
test('first-run coverage gaps survive close and later completed custom periods',t=>{const {store}=fixture(t);const other='@gaps';store.configure({version:1,account:other,preference:'all',timezone:'UTC'});store.import({version:1,account:other,start:'2025-12-01T00:00:00Z',end:'2025-12-02T00:00:00Z',coverage:{complete:false,gaps:['retention gap']},items:[]});store.close({version:1,account:other});assert.equal(store.window(other).start,'2025-12-01T00:00:00Z');store.import({version:1,account:other,start:'2025-12-03T00:00:00Z',end:now,coverage:{complete:true,gaps:[]},items:[]});store.close({version:1,account:other});assert.equal(store.window(other).start,'2025-12-01T00:00:00Z');store.import({version:1,account:other,start:'2025-12-01T00:00:00Z',end:now,coverage:{complete:true,gaps:[]},items:[]});store.close({version:1,account:other});assert.equal(store.read(other).coverage_gaps.length,0);assert.equal(store.window(other,{end:'2026-01-03T00:00:00Z'}).start,now);});
test('offset timestamps sort by actual instant and frozen source text stays unchanged',t=>{const {store,snapshot}=fixture(t);const other='@offsets';store.configure({version:1,account:other,preference:'all',timezone:'UTC'});const rows=[{...snapshot.items[0],occurred_at:'2026-01-01T12:00:00+11:00',post:{id:'same',verified:true,text:'original'}},{...snapshot.items[1],occurred_at:'2026-01-01T02:00:00Z',post:{id:'same',verified:true,text:'original'}}];const view=store.import({...snapshot,account:other,items:rows});assert.equal(view.items[0].source_id,'c0');const i=view.items[0];store.context({version:1,account:other,id:i.id,revision:0,evidence_ref:'read',source:{...i,safe:true,pending:true,available:true,text:'changed',context_complete:true}});assert.equal(store.status(other).batch.sources[0].text,'Comment 0');});
test('enriched parent identity regroups cards without rebinding editor IDs',t=>{const {store,snapshot}=fixture(t);store.configure({version:1,account:'@enrich',preference:'five',timezone:'UTC'});const result=store.import({...snapshot,account:'@enrich',items:snapshot.items.map(i=>({...i,post:{text:'initial context'},context_complete:false}))});for(const item of result.items)store.context({version:1,account:'@enrich',id:item.id,revision:item.revision,evidence_ref:'native-parent-read',source:{...item,safe:true,pending:true,available:true,context_complete:true,post:{id:'verified-parent',verified:true,text:'Full parent'}}});assert.equal(new Set(store.status('@enrich').items.map(i=>i.group)).size,1);assert.deepEqual(store.status('@enrich').items.map(i=>i.id),result.items.map(i=>i.id));});
