#!/usr/bin/env node
// Builds contract/tools.json, the snapshot of Threadify MCP tools the preflight checks skill text against.
// It reads the server's tool registry source (lib/threadify-mcp/tools.ts in lennoxsaint/threadify-app) and keeps,
// for each tool: its name, its required parameters and the four behaviour hints.
//
// Usage (from the repository root):
//   git -C <threadify-app> show <ref>:lib/threadify-mcp/tools.ts \
//     | node editions/listed/contract/extract.mjs --source "lennoxsaint/threadify-app@<sha>" > editions/listed/contract/tools.json
//   node editions/listed/contract/extract.mjs <tools.ts> --source <label> [--out <file>]
//
// Stopgap: ticket lennoxsaint/threadify-app#232 adds a JSON export generated from listThreadifyMcpTools() itself.
// When it lands, copy that export to contract/tools.json and delete this script. Until then this script reads the
// TypeScript source without running it. It understands the registry's own shapes only: `tool(name, title,
// description, schema, opts)` calls inside THREADIFY_MCP_TOOLS, `z.object({...})` schemas, spreads of top-level
// `const` objects, and `.optional()` / `.default()` chains. It mirrors the hint defaults of the `tool()` factory.
// An unrecognised shape stops the script instead of guessing.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { stableStringify } from '../build.mjs';

export const HINTS = ['readOnlyHint', 'destructiveHint', 'idempotentHint', 'openWorldHint'];
const NOTE = 'Generated by editions/listed/contract/extract.mjs from lib/threadify-mcp/tools.ts. '
  + 'Ticket lennoxsaint/threadify-app#232 replaces it with the server\'s exported JSON. Do not edit by hand.';

// Returns a copy of the source with comment and string contents blanked out (same length), so brackets and
// commas can be matched on it while values are read from the original.
export function mask(source) {
  const out = source.split('');
  const blank = (from, to) => { for (let i = from; i < to; i++) if (out[i] !== '\n') out[i] = ' '; };
  let i = 0;
  while (i < source.length) {
    const char = source[i];
    const next = source[i + 1];
    if (char === '/' && next === '/') { const end = source.indexOf('\n', i); const stop = end === -1 ? source.length : end; blank(i, stop); i = stop; continue; }
    if (char === '/' && next === '*') { const end = source.indexOf('*/', i + 2); if (end === -1) throw new Error('Unclosed block comment.'); blank(i, end + 2); i = end + 2; continue; }
    if (char === '\'' || char === '"' || char === '`') {
      let j = i + 1;
      while (j < source.length && source[j] !== char) {
        if (source[j] === '\\') j++;
        else if (char === '`' && source[j] === '$' && source[j + 1] === '{') throw new Error('Template literal expressions are not supported.');
        else if (char !== '`' && source[j] === '\n') throw new Error(`Unterminated string at offset ${i}.`);
        j++;
      }
      if (j >= source.length) throw new Error(`Unterminated string at offset ${i}.`);
      blank(i + 1, j);
      i = j + 1;
      continue;
    }
    i++;
  }
  return out.join('');
}

const OPEN = { '(': ')', '[': ']', '{': '}' };
const CLOSE = new Set([')', ']', '}']);

// Index just past the bracket that closes the one at `start`.
function closeOf(masked, start) {
  const stack = [];
  for (let i = start; i < masked.length; i++) {
    const char = masked[i];
    if (OPEN[char]) stack.push(OPEN[char]);
    else if (CLOSE.has(char)) {
      if (stack.pop() !== char) throw new Error(`Unbalanced bracket at offset ${i}.`);
      if (stack.length === 0) return i + 1;
    }
  }
  throw new Error(`Unclosed bracket at offset ${start}.`);
}

// Splits [from, to) at commas that sit at bracket depth zero; drops empty trailing parts.
function splitTop(masked, from, to) {
  const parts = [];
  let depth = 0;
  let start = from;
  for (let i = from; i < to; i++) {
    const char = masked[i];
    if (OPEN[char]) depth++;
    else if (CLOSE.has(char)) depth--;
    else if (char === ',' && depth === 0) { parts.push([start, i]); start = i + 1; }
  }
  parts.push([start, to]);
  return parts
    .map(([a, b]) => { while (a < b && /\s/.test(masked[a])) a++; while (b > a && /\s/.test(masked[b - 1])) b--; return [a, b]; })
    .filter(([a, b]) => b > a);
}

function stringValue(source, [a, b]) {
  const text = source.slice(a, b);
  if (!/^(['"])[\s\S]*\1$/.test(text)) throw new Error(`Expected a string literal, found: ${text.slice(0, 60)}`);
  return text[0] === '"' ? JSON.parse(text) : JSON.parse(`"${text.slice(1, -1).replace(/\\'/g, '\'').replace(/"/g, '\\"')}"`);
}

export function extractTools(source) {
  const masked = mask(source);
  // Top-level `const NAME = <expr>;` declarations, by name.
  const consts = new Map();
  for (const match of masked.matchAll(/^(?:export )?const (\w+)(?:\s*:[^=\n]+)?\s*=\s*/gm)) {
    const start = match.index + match[0].length;
    let depth = 0;
    let end = start;
    for (; end < masked.length; end++) {
      const char = masked[end];
      if (OPEN[char]) depth++;
      else if (CLOSE.has(char)) depth--;
      else if (char === ';' && depth === 0) break;
    }
    consts.set(match[1], [start, end]);
  }

  const span = (name) => {
    const found = consts.get(name);
    if (!found) throw new Error(`Unknown constant: ${name}`);
    return found;
  };

  // Field map of an object literal, a z.object(...) call or a constant naming either.
  const fields = (range, seen = new Set()) => {
    let [a, b] = range;
    const text = masked.slice(a, b);
    const ident = /^(\w+)$/.exec(text);
    if (ident) {
      if (seen.has(ident[1])) throw new Error(`Circular constant: ${ident[1]}`);
      return fields(span(ident[1]), new Set([...seen, ident[1]]));
    }
    const zObject = /^z\s*\.\s*object\s*\(/.exec(text);
    if (zObject) {
      const paren = a + zObject[0].length - 1;
      const inner = splitTop(masked, paren + 1, closeOf(masked, paren) - 1);
      if (inner.length !== 1) throw new Error('z.object() must take one object literal.');
      return fields(inner[0], seen);
    }
    if (masked[a] !== '{') throw new Error(`Unsupported schema shape: ${source.slice(a, Math.min(b, a + 60))}`);
    const result = new Map();
    for (const [x, y] of splitTop(masked, a + 1, closeOf(masked, a) - 1)) {
      const entry = masked.slice(x, y);
      const spread = /^\.\.\.\s*(\w+)$/.exec(entry);
      if (spread) { for (const [key, value] of fields(span(spread[1]), seen)) result.set(key, value); continue; }
      const keyed = /^(?:(\w+)|'(\w+)'|"(\w+)")\s*:\s*/.exec(entry);
      if (!keyed) throw new Error(`Unsupported object entry: ${source.slice(x, Math.min(y, x + 60))}`);
      result.set(keyed[1] ?? keyed[2] ?? keyed[3], [x + keyed[0].length, y]);
    }
    return result;
  };

  // True when the value's own call chain (not a nested argument) makes it optional.
  const optional = ([a, b], seen = new Set()) => {
    let depth = 0;
    for (let i = a; i < b; i++) {
      const char = masked[i];
      if (OPEN[char]) depth++;
      else if (CLOSE.has(char)) depth--;
      else if (depth === 0 && char === '.' && /^\.\s*(?:optional|default|nullish)\s*\(/.test(masked.slice(i, b))) return true;
    }
    const head = /^\s*(\w+)/.exec(masked.slice(a, b))?.[1];
    if (head && head !== 'z' && consts.has(head) && !seen.has(head)) return optional(span(head), new Set([...seen, head]));
    return false;
  };

  const booleans = (range) => {
    const out = {};
    for (const [key, [x, y]] of fields(range)) {
      const value = source.slice(x, y).trim();
      if (value !== 'true' && value !== 'false') throw new Error(`Hint ${key} must be a literal boolean.`);
      out[key] = value === 'true';
    }
    return out;
  };

  const [listStart, listEnd] = span('THREADIFY_MCP_TOOLS');
  if (masked[listStart] !== '[') throw new Error('THREADIFY_MCP_TOOLS must be an array literal.');
  const tools = [];
  for (const [x, y] of splitTop(masked, listStart + 1, closeOf(masked, listStart) - 1)) {
    const call = /^tool\s*\(/.exec(masked.slice(x, y));
    if (!call) throw new Error(`Unsupported registry entry: ${source.slice(x, Math.min(y, x + 60))}`);
    const paren = x + call[0].length - 1;
    const args = splitTop(masked, paren + 1, closeOf(masked, paren) - 1);
    if (args.length < 4 || args.length > 5) throw new Error(`tool() at offset ${x} must take 4 or 5 arguments.`);
    const name = stringValue(source, args[0]);
    const schemaFields = fields(args[3]);
    const required = [...schemaFields].filter(([, range]) => !optional(range)).map(([key]) => key).sort();
    let declared = null;
    if (args[4]) {
      const annotations = fields(args[4]).get('annotations');
      if (annotations) declared = booleans(annotations);
    }
    // Mirrors tool(): readOnly/destructive/openWorld default to false, and no annotations at all means a read.
    const hints = { readOnlyHint: false, destructiveHint: false, openWorldHint: false, ...(declared ?? { readOnlyHint: true }) };
    for (const key of Object.keys(hints)) if (!HINTS.includes(key)) throw new Error(`${name}: unknown hint ${key}.`);
    tools.push({ name, required, hints: Object.fromEntries(HINTS.map((key) => [key, hints[key] ?? null])) });
  }
  const names = new Set();
  for (const { name } of tools) {
    if (names.has(name)) throw new Error(`Duplicate tool name: ${name}`);
    names.add(name);
  }
  return tools.sort((p, q) => (p.name < q.name ? -1 : 1));
}

export function snapshot(source, label) {
  return stableStringify({ note: NOTE, source: label, tools: extractTools(source) });
}

function main(argv) {
  const sourceIndex = argv.indexOf('--source');
  const outIndex = argv.indexOf('--out');
  const label = sourceIndex === -1 ? null : argv[sourceIndex + 1];
  if (!label) { console.error('Usage: extract.mjs [<tools.ts>] --source <repo@sha> [--out <file>]'); return 2; }
  const skip = new Set([sourceIndex, sourceIndex + 1, outIndex, outIndex === -1 ? -1 : outIndex + 1]);
  const input = argv.find((arg, index) => !skip.has(index) && !arg.startsWith('--'));
  const source = fs.readFileSync(input ?? 0, 'utf8');
  const text = snapshot(source, label);
  if (outIndex === -1) process.stdout.write(text);
  else fs.writeFileSync(path.resolve(argv[outIndex + 1]), text);
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { process.exitCode = main(process.argv.slice(2)); }
  catch (error) { console.error(`Tool snapshot failed: ${error.message}`); process.exitCode = 1; }
}
